### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by BackuPs** [cedaro/infinite-wp-list-tables#1]
Hi 

A very nice plugin !!!

1) Can you please  remove the base64 image code from the js file as any antivirus or virus checker will goes bezeirk on this since most hacks on wordpress now are by base64 code injections and all those plugins turn on their red lights when they discover such code. Pls use a direct link to the image.

2) Can you add support for this on any custom posttypes like bbpress, CPT-Ui etc.?

3) is there a unminified version of the script?

Thanks
B.

**Comment by bradyvercher** [comment]
Thanks for the feedback @BackuPs!

The script is from a third party and I'm not interested in forking it to remove the base64 data, but I have gone ahead and bundled the unminified version to use when `SCRIPT_DEBUG` is enabled. You can find the [original repo here](https://github.com/infinite-scroll/infinite-scroll).

The plugin already worked with post, pages, users, and most custom post types, including bbPress. I've added support for comments and a couple of BuddyPress screens, and tested with WooCommerce, Easy Digital Downloads and Jetpack's portfolio CPT.

It should also work with most taxonomy (categories, tags) tables as well.
